# These are supported funding model platforms

github: patrickbrouwers
custom: https://www.paypal.com/donate/?token=kuWsCqWM4xcKIqd66cdJa5WFmIQ2vkxCydJ6QevQ_m2bMjWW9qZRl5rjqyMxP5sRhZjcv0&country.x=NL&locale.x=
