engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
    strings:
      - FIXME
      - TODO
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,unusedcode,codesize,naming,design,controversial"
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
  - ".github/"
  - "tests/"
  - "config/"