blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/Maatwebsite/Laravel-Excel/discussions
    about: Please ask and answer questions here.
  - name: Proposals
    url: https://github.com/Maatwebsite/Laravel-Excel/discussions
    about: Please place proposals here
